openapi: 3.0.0
info:
  title: sheepCRM API
  version: 1.0.0
servers:
  - url: https://sls-api-dev.sheepcrm.com
paths:

  /api/v2/find/person/{bucket}:
    $ref: 'requests/Person.yaml#/PersonFind'

  /api/v2{contact_uri}summary:
    $ref: 'requests/Contacts.yaml#/ContactSummary'

  /api/v2{person_uri}communications/detail:
    $ref: 'requests/Person.yaml#/PersonCommunicationsDetail'

  /api/v2{person_uri}personal/detail:
    $ref: 'requests/Person.yaml#/PersonPersonalDetail'

  /api/v2{person_uri}membership/all:
    $ref: 'requests/Person.yaml#/PersonMembershipAll'

  /api/v2{member_uri}:
    get:
      summary: Membership - single
      description: Get a summary of a single membership record (a member record), use the /detail endpoint to get the full details
      operationId: getMemberSummary
      parameters:
        - name: member_uri
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/member_uri'
      responses:
        '200':
          description: Successful operation

  /api/v2{member_uri}detail:
    get:
      summary: Membership - single detail
      description: Get a summary of the membership details for a person, use the /all endpoint to get the full details
      operationId: getMemberDetail
      parameters:
        - name: member_uri
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/member_uri'
      responses:
        '200':
          description: Successful operation

  /search/v2/{bucket}:
    get:
      summary: Search
      description: search across the whole system `/search/v2/{bucket}/?q=John+Smith`
      operationId: search
      parameters:
        - name: bucket
          in: path
          description: The bucket (client) name
          required: true
          schema:
            $ref: '#/components/schemas/bucket'
        - name: q
          in: query
          description: search string
          required: false
          schema:
            $ref: '#/components/schemas/q'
      responses:
        '200':
          description: A list of resource records matching the search terms
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResultsResponse'
        '400':
          description: a standard error message
        '401':
          description: Authentication error

  /notifications/v2/{bucket}:
    get:
      operationId: getNotifications
      summary: Notifications - list for user
      description: Get all notifications for the user ordered by date (new -> old)
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 7
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNotifications'
        '400':
          description: Bad request

  /notifications/v2/{bucket}/{resource_type}/{uid}:
    get:
      operationId: getSingleNotifications
      summary: Notifications - single
      description: Get a single notification
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request

  /notifications/v2/{bucket}/{resource_type}/{uid}/complete:
    put:
      operationId: completeSingleNotifications
      summary: Notifications - complete
      description: Mark a single notification as complete
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request

  /notifications/v2/{bucket}/{resource_type}/{uid}/snooze:
    put:
      operationId: snoozeSingleNotifications
      summary: Notifications - snooze
      description: Snooze a single notification for 24 hours or for 24 hours from now if overdue.
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request

components:
  schemas:
    bucket:
      type: string
      example: example

    uri:
      type: string
      example: /example/person/6305f074683e800f3abe809e/
      description: URIs are unique identifiers for resources in the system, they are structured as follows `/bucket/resource_type/uid/`

    member_uri:
      type: string
      example: /example/member/6305f074683e800f3abe809e/
      description: a member URI or 'membership' uri will always be in the format `/bucket/member/uid/` with the word 'member' in the middle

    q:
      type: string
      example: john smith

    SearchResultsResponse:
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              display_value:
                type: string
                example: John Smith
              id:
                type: string
                example: /example/person/6305f074683e800f3abe809e/
              primary_email:
                type: string
                example: john@smith.example.com
              primary_telephone:
                type: string
                example: +44 1234 56789
              resource:
                type: string
                example: person

    getNotifications:
      type: object
      properties:
        notification:
          type: object
          properties:
            assigned_to:
              type: string
            assigned_to_display:
              type: string
            body:
              type: string
            context:
              type: string
            context_display:
              type: string
            created:
              type: string
            creator:
              type: string
            creator_reference:
              type: string
            date:
              type: string
            display_value:
              type: string
            entity:
              type: string
            entry_subtype:
              type: string
            entry_type:
              type: string
            files:
              type: array
              items:
                type: string
            last_updated:
              type: string
            link:
              type: string
            record_state:
              type: string
            star:
              type: boolean
            tags:
              type: array
              items:
                type: string
            text_body:
              type: string
            title:
              type: string
            uid:
              type: string
            uri:
              type: string
            user_interface:
              type: object
              properties:
                can_create_journal:
                  type: boolean
                can_delete_journal:
                  type: boolean
                can_edit_journal:
                  type: boolean
                can_restore_journal:
                  type: boolean
                policy_name:
                  type: string

