openapi: 3.0.0
info:
  title: SheepNotifications API
  version: 1.0.0
servers:
  - url: https://sls-api-dev.sheepcrm.com
paths:
  /notifications/v2/{bucket}:
    get:
      operationId: getNotifications
      summary: Get all notifications for the user
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNotifications'
        '400':
          description: Bad request

  /notifications/v2/{bucket}/{resource_type}/{uid}:
    get:
      operationId: getSingleNotifications
      summary: Get a single notification
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /notifications/v2/{bucket}/{resource_type}/{uid}/complete:
    put:
      operationId: completeSingleNotifications
      summary: Mark a single notification as complete
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
  /notifications/v2/{bucket}/{resource_type}/{uid}/snooze:
    put:
      operationId: snoozeSingleNotifications
      summary: Snooze a single notification for 24 hours or for 24 hours from now if overdue.
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: resource_type
          in: path
          required: true
          schema:
            type: string
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request

components:
  schemas:
    getNotifications:
      type: object
      properties:
        notification:
          type: object
          properties:
            assigned_to:
              type: string
            assigned_to_display:
              type: string
            body:
              type: string
            context:
              type: string
            context_display:
              type: string
            created:
              type: string
            creator:
              type: string
            creator_reference:
              type: string
            date:
              type: string
            display_value:
              type: string
            entity:
              type: string
            entry_subtype:
              type: string
            entry_type:
              type: string
            files:
              type: array
              items:
                type: string
            last_updated:
              type: string
            link:
              type: string
            record_state:
              type: string
            star:
              type: boolean
            tags:
              type: array
              items:
                type: string
            text_body:
              type: string
            title:
              type: string
            uid:
              type: string
            uri:
              type: string
            user_interface:
              type: object
              properties:
                can_create_journal:
                  type: boolean
                can_delete_journal:
                  type: boolean
                can_edit_journal:
                  type: boolean
                can_restore_journal:
                  type: boolean
                policy_name:
                  type: string